=== Alcaro/OnlineTools/scripts/tool.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "title": "Online Tool",
    "type": "object",
    "required": ["name", "game", "description", "authors", "dependencies"],
    "properties": {
        "name": {
            "description": "User-friendly name of the tool, shown on the Online Tools page.",
            "type": "string"
        },
        "game": {
            "description": "Which game is this tool relevant for?",
            "type": "string",
            "enum": ["general", "smw", "yi", "sm64"]
        },
        "description": {
            "description": "A short description of the tool's purpose. More detailed instructions should be included in the tool itself.",
            "type": "string"
        },
        "authors": {
            "type": "array",
            "items": {"$ref": "#/definitions/author"}
        },
        "dependencies": {
            "description": "Dependencies to be automatically loaded before the tool runs.",
            "type": "array",
            "items": {"$ref": "#/definitions/dependency"}
        }
    },
    "additionalProperties": false,
    "definitions": {
        "author": {
            "type": "object",
            "required": ["name"],
            "properties": {
                "name": {
                    "description": "The author's name, usually their current username on SMW Central.",
                    "type": "string"
                },
                "user": {
                    "description": "The author's user ID on SMW Central if they have an account.",
                    "type": "number"
                }
            },
            "additionalProperties": false
        },
        "dependency": {
            "description": "A dependency loaded from cdnjs",
            "type": "object",
            "required": ["type", "library", "version", "file"],
            "properties": {
                "type": {
                    "description": "Is the dependency a CSS or JS file?",
                    "type": "string",
                    "enum": ["style", "script"]
                },
                "library": {"type": "string"},
                "version": {"type": "string"},
                "file": {"type": "string"}
            },
            "additionalProperties": false
        }
    }
}

=== Alcaro/OnlineTools/src/circletool/tool.json
{
    "name": "Circle Tool (Pendulum)",
    "game": "smw",
    "description": "Circle Tool customizes the trajectory of the [url=https://www.smwcentral.net/?p=section&s=smwsprites&f%5Bname%5D=pendulum]Pendulum[/url] sprites.",
    "authors": [
        {"name": "Alcaro", "user": 1686},
        {"name": "Telinc1", "user": 15661}
    ],
    "dependencies": []
}

=== Alcaro/OnlineTools/src/pal_generator/tool.json
{
    "name": ".pal Generator",
    "game": "smw",
    "description": "Creates .pal files from screenshots of Lunar Magic's palette editor. May or may not be useful when you edit palettes in an external tool and don't want to copy each color back over manually.",
    "authors": [
        {"name": "WhiteYoshiEgg", "user": 951}
    ],
    "dependencies": []
}
